language: python
python:
    - '2.7'
    - '3.3'
    - 'pypy'
env:
    global:
        - STEAM_API_KEY=$(echo "MTI2Njc1RDNENEJDOUU5QzVBMTBEQjJDMTdDQUNFOTI="|base64 -d)
script: python setup.py test
notifications:
    email:
        on_success: never
        on_failure: change
    irc:
        channels:
            - "chat.freenode.net#optf2"
        template:
            - "%{repository}/%{branch}#%{commit} by %{author}: %{message} - %{build_url}"
sudo: false
